const mongoose = require('mongoose');

const InformeHospitalAMinisterio = new mongoose.Schema({
	ReporteHospitalario:{
		idCentro:{
			type:Number,
			required:true,
		},
		nombreHospital:{
			type:String,
			required:true,
		},
		ciudad:{
			type:String,
			required:true,
		},
		resumenCasos:{
			cantidadMuertos:{
				type:Number,
				required:true
			},
			pacientesCurados:{
				type:Number,
				required:true
			},
			pacientesEnfermos:{
				type:Number,
				required:true
			}
		},
		testRealizados:{
			realizadas:{
				type:Number,
				required:true
			},
			sinResultado:{
				type:Number,
				required:true
			},
			positivos:{
				type:Number,
				required:true
			},
			negativos:{
				type:Number,
				required:true,
			}
		},
		Recursos:{
			camillasDisponibles:{
				type:Number,
				required:true
			},
			camillasOcupadas:{
				type:Number,
				required:true
			},
			jabonLitros:{
				type:Number,
				required:true
			},
			alcoholLitros:{
				type:Number,
				required:true
			},
			barbijos:{
				type:Number,
				required:true
			},
			jeringas:{
				type:Number,
				required:true
			},
			cofias:{
				type:Number,
				required:true
			}
		}
	}    
});
module.exports = mongoose.model('InformeHospitalAMinisterio',InformeHospitalAMinisterio );
